# Generated by Django 6.1 on 2026-09-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_start_price_alter_rate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.genre'),
        ),
        migrations.AddField(
            model_name='rate',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
